name: Conditional Replace and Set Env

on:
  workflow_dispatch:
    inputs:
      input_text:
        description: 'Text input where replacement will happen if condition is met'
        required: true
        default: 'hello foo world'

jobs:
  conditional-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for keyword and replace if found
        id: check_and_replace
        run: |
          echo "Input: $INPUT_TEXT"

          if [[ "$INPUT_TEXT" == *AA-BB-CC-PROD* ]]; then
            echo "Condition met: 'foo' found in input."
            MODIFIED_TEXT="${INPUT_TEXT//PROD/STG}"
            echo "Modified text: $MODIFIED_TEXT"
            echo "MODIFIED_TEXT=$MODIFIED_TEXT" >> $GITHUB_ENV
            echo "modified_text=$MODIFIED_TEXT" >> $GITHUB_OUTPUT
          else
            echo "Condition not met: 'foo' not found in input."
            MODIFIED_TEXT="${INPUT_TEXT//PROD/STAGE}"
            echo "Modified text: $MODIFIED_TEXT"
            echo "MODIFIED_TEXT=$MODIFIED_TEXT" >> $GITHUB_ENV
            echo "modified_text=$MODIFIED_TEXT" >> $GITHUB_OUTPUT
          fi
        env:
          INPUT_TEXT: ${{ github.event.inputs.input_text }}

      - name: Use environment variable
        run: |
          echo "Using the modified environment variable:"
          echo "MODIFIED_TEXT=$MODIFIED_TEXT"
